### PR TITLE
Fix for token issue

### LINKED ISSUE #68: script doesn't found update on plexpass channel
when I run 
/plexupdate.sh -p -c -a 2>&1 1>/var/log/plexupdate

no new update are found. But on my server I got a message which say new update available!

I'm on the Plexpass channel..

### PR DESCRIPTION
**Pull request by Tommatheussen**
It seems that Plex changed how you can access their Plexpass download channels. This fix gets the token from the Sign in response, and sets it as a token in the download request.

It can probably be optimised or be done different, but this is just a quick fix (which works for me)

This should fix #68

### CODE REVIEW

File: plexupdate.sh [hunk 1]
```diff
@@ -302,6 +302,11 @@ if [ "${KEEP}" != "yes" -o ! -f /tmp/kaka ] && [ "${PUBLIC}" == "no" ]; then
 		cat /tmp/failcause >&2
 		exit 1
 	fi
+
```
Comment (sjorge) [inline plexupdate.sh]: This line only has whitespaces on it, those should probably be removed.

**Comment by mrworf** [comment]
Thanks!
