### PR TITLE
Fix PATH on Ubuntu systems if dpkg is likely to fail during AUTOINSTALL

### LINKED ISSUE #97: AUTOINSTALL fails when run from cron
Just started noticing this a few days ago and I'm guessing it was just getting silently ignored before the change to output handling for -c:

```
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
```

The problem is that `PATH` doesn't include `/sbin` when running in cron. This can be fixed by the user by just redefining `PATH` inside their crontab, but that could possibly have unintended consequences with other jobs.

Since both of these are being called from within `dpkg`, we can't call them "correctly" from inside plexupdate, so that just leaves two options:

1. Use `hash` to manually point `ldconfig` and `start-stop-daemon` at `/sbin`. Doesn't affect the `PATH` or any other applications directly, but it could fail if `dpkg` tries to call something other than `ldconfig` or `start-stop-daemon`, or if it calls them from within a subshell.

2. `export` an updated `PATH` before running `DISTRO_INSTALL`. Should work regardless, but it could (theoretically) have unintended consequences elsewhere in the script. (it would only be set if running in cron mode, so it **should** be fine)

Any thoughts or pros/cons for either approach before I send in a PR? (I personally prefer option 1 but I think 2 might be more foolproof.)

### PR DESCRIPTION
**Pull request by demonbane**
Intentionally kept this simple. If ldconfig can't be found and we're running on ubuntu, just add /sbin to the PATH and continue on as normal. Any error output will still be generated by dpkg once it runs, but this should prevent that in most cases.

Fixes #97

### CODE REVIEW

File: plexupdate.sh [hunk 1]
```diff
@@ -548,6 +548,11 @@ if [ ! -z "${PLEXSERVER}" -a "${AUTOINSTALL}" = "yes" ]; then
 fi
 
 if [ "${AUTOINSTALL}" = "yes" ]; then
+	if ! hash ldconfig 2>/dev/null && [ -x /sbin/ldconfig -a "${DISTRO}" = "ubuntu" ]; then
```
Comment (mrworf) [inline plexupdate.sh]: Why the extra check?

Comment (demonbane) [inline plexupdate.sh]: Oh, that's a leftover from when I first started writing the patch. The original version tried much harder to do the right thing in every case but it turned into a 30+ line block of code pretty quickly. When I simplified it to just allow dpkg to error out anyway, I forgot to take it out. I can pull it out if you want to keep the code slightly cleaner.

Comment (mrworf) [inline plexupdate.sh]: Lets take it out and then I'll merge. Looks good to me otherwise

File: plexupdate.sh [hunk 2]
```diff
@@ -548,7 +548,7 @@ if [ ! -z "${PLEXSERVER}" -a "${AUTOINSTALL}" = "yes" ]; then
 fi
 
 if [ "${AUTOINSTALL}" = "yes" ]; then
-	if ! hash ldconfig 2>/dev/null && [ -x /sbin/ldconfig -a "${DISTRO}" = "ubuntu" ]; then
+	if ! hash ldconfig 2>/dev/null && [ -a "${DISTRO}" = "ubuntu" ]; then
```
Comment (mrworf) [inline plexupdate.sh]: I'm still not understanding why we would limit this to ubuntu? Also, the -a isn't needed

Comment (demonbane) [inline plexupdate.sh]: Whoops, the -a is a typo, fixed.

The check for Ubuntu is because the thing that's failing is dpkg. Since RH doesn't use dpkg AFAIK, the fix isn't needed there so we avoid tampering with the PATH. If RH is also failing through some other mechanism we can fix that here as well, I just don't know if that's the case or not.

Comment (mrworf) [inline plexupdate.sh]: Fair enough :)
